---
debug:
  level: trace
twitter:
  consumer_key:
  consumer_secret:
  access_token:
  access_token_secret:
  timeout_ms: 60000
gdax:
  key:
  secret:
  passphrase:
  pairs:
  - BTC-USD
debounce: 600000 # 10 minutes
