---
timezone: America/Los_Angeles
recipes:
  all-time-high:
    - gdax
    - twitter
    - media
  # tracker:
  #   - gdax
  metrics:
    - gdax
debug:
  level: trace
twitter:
  consumer_key:
  consumer_secret:
  access_token:
  access_token_secret:
  timeout_ms: 60000
gdax:
  key:
  secret:
  passphrase:
  pairs:
    - BTC-USD
metrics:
  port: 10080
  host: 0.0.0.0
debounce: 600000 # 10 minutes
